### ISSUE TITLE
Was working but now starts and shuts down

### ISSUE THREAD

**Issue by Mclaneinc** [WilfredC64/sid-device#2]
Did work but now starts and crashes if you put a mouse pointer over it. The fact it worked initially makes it seem an issue with my machine. Any idea's..

Win 10, virus free, all the latest drivers..Just weird... Nothing new installed since it was working..

**Comment by WilfredC64** [comment]
Can you please check Task Manager and see if another sid-device is still running? If so, end the task and then try to start sid-device again.

**Comment by Mclaneinc** [comment]
That's the odd thing, even when a single version of it seems to be running (icon visible) the task manager does not show it as running, there's no sid-device process. I've had a situation where theres 4 icons showing but as soon as I put the mouse pointer near them, they all close.

I did find a dmp file from the crash if that helps.

I've re-downloaded the file and replaced it but it still occurs, I've cleared out any mentions in the registry and the two mentions in the roaming data, still the same?

**Comment by WilfredC64** [comment]
It seems like this is related in reading/writing the config.json file.

Can you please upload your config.json file here? To find it, start Windows Explorer and go to location: %AppData%\siddevice\siddevice

Please save file config.json first to some location so we can investigate. Then delete the file and try to start sid-device. Does it run now?

The only way I could simulate a crash like you have is when I make the config.json file read-only first and then change a setting in the Settings dialog. I was not able to let sid-device crash when I corrupt the config.json file and start sid-device. Hopefully your config.json file gives me more info.

If deleting the config.json doesn't solve the problem, can you please let me know the location where you have sid-device installed? Can you please try to copy it to some other folder, not in program files or network drive, and see if it starts correctly?

**Comment by Mclaneinc** [comment]
It's not even creating that file, it did have one originally but I deleted it to see if it would fix the issue..

I tried the sid-device from a non networked location and it shows the icon and then when I go to put the mouse over then it just shuts down, but because it's not creating the config I doubt its even running properly. I've checked my anti virus and even made it an exception from being scanned and still nothing. I have no clue but I know it did work as I played a few tunes via Acid64 or whatever its called and all was fine, so I doubt it's anything to do with anything on your side. I've scanned the PC numerous times with Malware bytes (free version) and nothing. At a loss, I'm very careful about what goes on my PC, no cracked stuff. If I don't get any joy I'll start from scratch, full format etc and see if that fixes it, if it does, I'll drop a message here

**Comment by WilfredC64** [comment]
I think you did uninstall the WebView2 runtime or something happened with it. Can you please (re)install WebView 2?

https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

This is a prerequisite to run SID-Device. I forgot to mention it in the readme of the release. I will update the readme in the next release. WebView 2 is pre-installed on Windows 11 but not on Windows 10.

**Comment by Mclaneinc** [comment]
Excellent, now works..

Thank you for your hard work, yes I most likely did uninstall it as I don't favour the Edge browser, so anything looking like an add on would have been dropped by me..

Sorry for the hassle but hopefully it may help others..

**Comment by WilfredC64** [comment]
No problem. I'm glad it works again for you.

**Comment by Mclaneinc** [comment]
That's the odd thing, even when a single version of it seems to be running
(icon visible) the task manager does not show it as running, there's no
sid-device process. I've had a situation where theres 4 icons showing but
as soon as I put the mouse pointer near them, they all close.

I did find a dmp file from the crash if that helps.

I've re-downloaded the file and replaced it but it still occurs, I've
cleared out any mentions in the registry and the two mentions in the
roaming data, still the same?
